version: "3"
services:
  web:
    container_name: socialMediaPlatformService
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      - MONGO_HOST=mongodb://db:27017
      - MONGO_DB=social-media-platform
      - JWT_SECRET=JwtSecretTokenWillBeHere
      - JWT_EXPIRATION=120h
      - APPLICATION_SERVER_PORT=3000
      - APP_FORCE_SHUTDOWN_SECOND=30

  # Database
  db:
    container_name: socialMediaPlatformServiceMongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
